name: razum_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: any
  flutter_bloc: any
  chopper: any
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: any
  chopper_generator: any
  json_serializable: any

flutter:
  uses-material-design: true
